---
title: "R and textbook resources for ENV H 543"
author: "Brian High"
date: "4/07/2016"
output:
  html_document:
    toc: true
    theme: united
    keep_md: yes
    self-contained: yes
---

## RStudio Server: "Phage"

Phage is a DEOHS server running RStudio Server as a web application.

https://phage.deohs.washington.edu/

## eBooks

### Quantitative microbial risk assessment

Provides the latest QMRA methodologies to determine infection risk cause by 
either accidental microbial infections or deliberate infections caused by terrorism

- Reviews the latest methodologies to quantify at every step of the microbial
exposure pathways, from the first release of a pathogen to the actual human
infection
- Provides techniques on how to  gather information, on how each microorganism 
moves through the environment, how to determine their survival rates on various
media, and how people are exposed to the microorganism
- Explains how QMRA can be used as a tool to measure the impact of interventions 
and identify the best policies and practices to protect public health and safety
- Includes new information on genetic methods
- Techniques use to develop risk models for drinking water, groundwater, 
recreational water, food and pathogens in the indoor environment

[Quantitative microbial risk assessment](http://alliance-primo.hosted.exlibrisgroup.com/UW:all:CP51230982940001451), Charles N. Haas Joan B. Rose; Charles P. Gerba. 2014  Hoboken, New Jersey: Wiley.

### Microbiological Risk Assessment in Food Processing

- Provides a detailed coverage of the key steps in MRA and how it can be used to improve food safety
- A standard work on one of the most important aspects of food safety management

[Microbiological Risk Assessment in Food Processing](http://alliance-primo.hosted.exlibrisgroup.com/UW:all:CP71155643330001451), Martyn Brown; Michael Stringer, 1950-.
2002 Boca Raton, Fla. : CRC Press ; Cambridge, England : Woodhead Pub.

### EnvStats

- EnvStats is a comprehensive R software library for environmental scientists,
engineers, and regulators, based on the open-source statistics and graphics 
package R.
- This book shows how to use EnvStats to easily produce powerful graphical and 
statistical analyses of environmental data.
- Includes extensive examples using data sets from regulatory guidance documents.

[EnvStats](http://offcampus.lib.washington.edu/login?url=http://link.springer.com/book/10.1007/978-1-4614-8456-1), An R Package for Environmental Statistics, Steven P. Millard. 2013 New York: Springer.

### Beginning Data Science with R

- Introduces fundamental data science methodologies using the R programming language
- Covers concepts through real-world datasets and case studies
- Examines cutting edge topics in both research and commercial applications

[Beginning Data Science with R](http://alliance-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?vid=UW&search_scope=all&docId=dedupmrg490691634&fn=permalink), Manas A. Pathak. 2014 Cham: Springer International Publishing.

### R by Example

- Example-based introduction to the statistical computing environment
- Does not assume any previous familiarity with R or other software packages
- R functions are presented in the context of interesting applications with real data

[R by Example](http://alliance-primo.hosted.exlibrisgroup.com/UW:all:CP71109296790001451), 
Jim Albert; Maria L. Rizzo. 2012 New York : Springer.

[Code samples](http://personal.bgsu.edu/~mrizzo/Rx/Rx.code.R) at instructor's website.

[Udemy course on Monte Carlo Simulation with R](https://www.udemy.com/r-programming-for-simulation-and-monte-carlo-methods/learn/v4/overview) based on _R by Example_

### Introducing Monte Carlo Methods with R

The book covers:

- Basic random generation algorithms
- Monte Carlo techniques for integration and optimization
- Convergence diagnoses
- Markov chain Monte Carlo methods

[Introducing Monte Carlo Methods with R](http://alliance-primo.hosted.exlibrisgroup.com/UW:all:CP71173371900001451), Christian P. Robert; George Casella. 2010 New York : Springer.

### Mastering Scientific Computing with R

What You Will Learn:

- Master data management in R
- Perform hypothesis tests using both parametric and nonparametric methods
- Understand how to perform statistical modeling using linear methods
- Model nonlinear relationships in data with kernel density methods
- Use matrix operations to improve coding productivity
- Utilize the observed data to model unobserved variables
- Deal with missing data using multiple imputations
- Simplify high-dimensional data using principal components, singular value decomposition, and factor analysis
- Monte Carlo simulation in one and two dimensions with the mc2d package

[Mastering Scientific Computing with R](http://shop.oreilly.com/product/9781783555253.do), Gerrard P., Johnson R. M. 2015 Packt Publishing.

See [Chapter 8. Simulations](https://books.google.com/books?id=MI92BgAAQBAJ&lpg=PA285&ots=FRoO7PRGIU&dq=%22Chapter%208.%20Simulations%22&pg=PA285#v=onepage&q=%22Chapter%208.%20Simulations%22&f=false) for details on the use of the mc2d package and several examples.

You can [access this eBook without  cost](http://ezproxy.spl.org:2048/login?url=http://proquest.safaribooksonline.com/9781783555253) 
if you have a Seattle Public Library [card](http://www.spl.org/using-the-library/get-started/get-a-library-card).

### R for Stata Users

- This book shows you how to extend the power of Stata through the use of R. 
- It introduces R using Stata terminology with which you are already familiar. 
- It steps through more than 30 programs written in both languages, comparing and contrasting the two packages' different approaches. 
- When finished, you will be able to use R in conjunction with Stata, or separately, to import data, manage and transform it, create publication quality graphics, and perform basic statistical analyses.

[R for Stata users](http://alliance-primo.hosted.exlibrisgroup.com/UW:all:CP71161669170001451)
Robert A. Muenchen, Joseph M. Hilbe. 2010 New York : Springer.

## R Resources

- [Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
- [Swirl](http://swirlstats.com/students.html)
- [R Markdown](http://rmarkdown.rstudio.com/)